### ISSUE TITLE
Yêu cầu phần mềm

### ISSUE THREAD

**Issue by abn-volk** [ntgiang71096/Typing-Tutor#3]
Mọi người xem thế này đã đủ chưa:

Các bài tập đánh máy
- Luyện từng cặp phím: fj, dk, sl, a;, v.v.
- Luyện cả hàng phím: hàng cơ sở, trên, dưới, số
- Luyện đánh văn bản

Người dùng
- Đăng nhập bằng Facebook
- Theo dõi chỉ số WPM/CPM, số từ/đoạn đã đánh
- Biểu đồ?
- Mục tiêu hàng ngày? (Ví dụ 1000 từ, 20 đoạn văn...)
- Xếp hạng, thêm bạn? (Nếu phức tạp quá thì bỏ ngay và luôn)
- Hệ thống tính điểm (EXP) cho giống trò chơi?

Dữ liệu
- Bài đánh từng cặp phím, hàng phím: tự làm :))
- Văn bản: Các tác phẩm văn học thuộc phạm vi công cộng (public domain), đỡ dính bản quyền (khoe với thầy là bọn em tuân thủ đạo đức nghề nghiệp, hí hí)
- CSDL về người dùng: Lưu những gì?

**Comment by ntgiang71096** [comment]
Phần CSDL trước mắt t thấy cần 2 bảng là bảng user và bảng activity, chi tiết t sẽ xem xét và báo lại sau
